Controllers/EnquiryController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using EeshaProperty.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using EeshaProperty.Areas.Identity.Data;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using EeshaProperty.Data;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using EeshaProperty.Services;
using ExcelDataReader;
using System.Net;
using AutoMapper.Configuration;

namespace EeshaProperty.Controllers
{
    [Authorize]
    public class EnquiryController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _repository;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IMailService _emailSender;
        private static int count = 0;
        private static bool Inserted = false;
        public Microsoft.Extensions.Configuration.IConfiguration _configuration;

        public EnquiryController(ILogger<HomeController> logger,
                                ApplicationDbContext repository,
                                IWebHostEnvironment webHostEnvironment,
                                UserManager<ApplicationUser> userManager,
                                IMailService emailSender,
                                Microsoft.Extensions.Configuration.IConfiguration config)
        {
            _logger = logger;
            _repository = repository;
            _webHostEnvironment = webHostEnvironment;
            _userManager = userManager;
            _emailSender = emailSender;
            _configuration = config;
        }

        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);
            var userrole = await _userManager.IsInRoleAsync(user, "admin");

            if (userrole)
            {
                var Enquiries = await _repository.Enquiries.ToListAsync();
                return View(Enquiries);
            }
            else
            {
                var Enquiries = await _repository.Enquiries.Where(p => p.EmpCode == user.EmployeeCode).ToListAsync();
                return View(Enquiries);
            }
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public IActionResult EmailCampain()
        {
            return View();
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public IActionResult SMSCampain()
        {
            return View();
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> SendEmails(string subject, string mailContent)
        {
            var enquiries = await _repository.Enquiries.ToListAsync();

            foreach (var e in enquiries)
            {
                if (subject != null && mailContent != null)
                {
                    _emailSender.SendEmail(Mail.DNR, e.Email, e.FullName, subject, mailContent);
                }
            }

            return Json("mail has been sent");
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> SendSMS(string message)
        {
            var enquiries = await _repository.Enquiries.ToListAsync();

            foreach (var e in enquiries)
            {
                var PhoneNumber = e.PhoneNumber;
                var AlternateNo = e.AlternateNo;
                
                var sURL = _configuration["SmsUrl"].ToString() +
                "username=" + _configuration["SMSUser"].ToString() +
                "&message=" + message +
                "&sendername=" + _configuration["SenderName"].ToString() +
                "&smstype=" + _configuration["SmsType"].ToString() +
                "&numbers=" + PhoneNumber +
                "&apikey=" + _configuration["ApiKey"].ToString();

                try
                {
                    using (WebClient client = new WebClient())
                    {

                        string s = client.DownloadString(sURL);

                        var responseObject = Newtonsoft.Json.JsonConvert.DeserializeObject<RootObject>(s);
                        int n = responseObject.Status;
                        // if (n == 3)
                        // {
                        //     Json("Message does not Send Successfully due to invalid credentials");
                        // }
                        // else
                        // {
                        //     Json("Message Send Successfully !");                        
                        // }
                    }
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "Error in sending Message");
                    ex.ToString();
                }

            }

            return Json("sms has been sent");
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.StateId = new SelectList(_repository.States, "Id", "StateName");
            return View();
        }

        [HttpGet]
        public JsonResult LoadCities(int id)
        {
            var cities = _repository.Cities.Where(p => p.StateId == id).ToList();
            return Json(new SelectList(cities, "Id", "CityName"));
        }

        [HttpPost]
        public async Task<IActionResult> Create(Enquiry enquiry)
        {
            if (ModelState.IsValid)
            {
                // if (enquiry.CityId <= 0 || enquiry?.CityId == null)
                // {
                //     ModelState.AddModelError(string.Empty, "Please select city and try again.");
                //     ViewBag.StateId = new SelectList(_repository.States, "Id", "StateName", enquiry.StateId);
                //     ViewBag.CityId = new SelectList(_repository.Cities, "Id", "CityName", enquiry.CityId);
                //     return View(enquiry);
                // }

                var user = await _userManager.GetUserAsync(User);

                enquiry.CreatedBy = user.UserName;
                enquiry.Username = user.UserName;
                enquiry.CreatedDate = DateTime.Now;
                enquiry.EmpCode = user.EmployeeCode;

                _repository.Enquiries.Add(enquiry);
                await _repository.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            ViewBag.StateId = new SelectList(_repository.States, "Id", "StateName", enquiry.StateId);
            ViewBag.CityId = new SelectList(_repository.Cities, "Id", "CityName", enquiry.CityId);
            return View(enquiry);
        }


        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NoContent();
            }
            Enquiry enquiry = await _repository.Enquiries.FindAsync(id);
            return View(enquiry);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NoContent();
            }

            Enquiry enquiry = await _repository.Enquiries.FindAsync(id);

            ViewBag.StateId = new SelectList(_repository.States, "Id", "StateName", enquiry.StateId);
            ViewBag.CityId = new SelectList(_repository.Cities.Where(p => p.StateId == enquiry.StateId), "Id", "CityName", enquiry.CityId);

            return View(enquiry);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Enquiry enquiry)
        {
            if (ModelState.IsValid)
            {
                // if (enquiry.CityId <= 0 || enquiry?.CityId == null)
                // {
                //     ModelState.AddModelError(string.Empty, "Please select city and try again.");
                //     ViewBag.StateId = new SelectList(_repository.States, "Id", "StateName", enquiry.StateId);
                //     ViewBag.CityId = new SelectList(_repository.Cities, "Id", "CityName", enquiry.CityId);
                //     return View(enquiry);
                // }

                var user = await _userManager.GetUserAsync(User);

                enquiry.UpdatedBy = user.UserName;
                enquiry.UpdatedDate = DateTime.Now;

                _repository.Entry(enquiry).State = EntityState.Modified;
                await _repository.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.StateId = new SelectList(_repository.States, "Id", "StateName", enquiry.StateId);
            ViewBag.CityId = new SelectList(_repository.Cities, "Id", "CityName", enquiry.CityId);
            return View(enquiry);
        }

        //[Authorize(Roles = "admin")]
        [HttpGet]
        public IActionResult BulkUpload()
        {
            if (Inserted)
            {
                if (count <= 0)
                    ViewBag.RecordSaved = "No records has been inserted";
                else
                    ViewBag.RecordSaved = count + " Records successfully inserted";

                count = 0;
                Inserted = false;
            }

            return View();
        }

        //[Authorize(Roles = "admin")]
        [HttpPost]
        public async Task<IActionResult> BulkUpload(EnquiryViewModel model)
        {
            if (ModelState.IsValid)
            {
                // if (model.Month == "" || model.Month == null)
                // {
                //     ModelState.AddModelError(string.Empty, "Please select month and try again.");
                //     return View(model);
                // }

                // if (model.Year < 2019)
                // {
                //     ModelState.AddModelError(string.Empty, "Please select year and try again.");

Views/Reports/Index.cshtml
@using EeshaProperty.Data
@using EeshaProperty.Areas.Identity.Data
@using Microsoft.AspNetCore.Identity

@inject ApplicationDbContext _repository
@inject UserManager<ApplicationUser> userManager
@inject SignInManager<ApplicationUser> SignInManager

@{
    ViewData["Title"] = "Report Dashboard";
    ViewData["ActivePage"] = "Dashboard";
    var user = await userManager.GetUserAsync(User);
    var isAdmin = !SignInManager.IsSignedIn(User) ? false : await userManager.IsInRoleAsync(user,"admin");
    
    var enquiries = isAdmin 
    ? _repository.Enquiries.ToList()
    : _repository.Enquiries.Where(p => p.EmpCode == user.EmployeeCode).ToList();
}

<div class="row">
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
        <div id="cardbox1">
            <div class="statistic-box">
                <i class="fa fa-calendar fa-3x"></i>
                <div class="counter-number pull-right">
                    <span class="count-number">@enquiries?.Count()</span>
                </div>
                <h3>Total Enquiries</h3>
            </div>
        </div>        
    </div>
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
        <div id="cardbox1">
            @{
                var today = DateTime.Today;
                var month = new DateTime(today.Year, today.Month, 1);       
                var first = month.AddMonths(-1);
                var last = month.AddDays(-1);
                var lMonthCount = enquiries.Where(p => p.CreatedDate.Date >= first.Date && p.CreatedDate.Date <= last.Date).Count();
            }
            <div class="statistic-box">
                <i class="fa fa-calendar-o fa-3x"></i>
                <div class="counter-number pull-right">
                    <span class="count-number">@lMonthCount</span>
                </div>
                <h3>Last Month Enquiries</h3>
                <p>From @first.ToString("dd MMM yyyy") To @last.ToString("dd MMM yyyy")</p>
            </div>
        </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
        <div id="cardbox1">
            @{
                DateTime mondayOfLastWeek = DateTime.Today.AddDays(-(int)DateTime.Today.DayOfWeek - 6);
                DateTime sundayOfLastWeek = mondayOfLastWeek.AddDays(6);
                var lWeekCount = enquiries.Where(p => p.CreatedDate.Date >= mondayOfLastWeek.Date && p.CreatedDate.Date <= sundayOfLastWeek.Date).Count();
            }
            <div class="statistic-box">
                <i class="fa fa-calendar-plus-o fa-3x"></i>
                <div class="counter-number pull-right">
                    <span class="count-number">@lWeekCount</span>

                </div>
                <h3>Last Week Enquiries</h3>
                <p>From @mondayOfLastWeek.ToString("dd MMM yyyy") To @sundayOfLastWeek.ToString("dd MMM yyyy")</p>
            </div>
        </div>
    </div>

</div>

Views/Reports/LocationWise.cshtml
@model IEnumerable<Enquiry>

@{
    ViewData["Title"] = "Location Report";
    ViewData["ActivePage"] = "Reports";    
}

<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-bd ">
            <div class="panel-heading">
                <div class="btn-group" id="buttonlist">
                    Location Report
                </div>
            </div>
            <div class="panel-body">
                <form class="col-sm-12">
                    <div class="col-sm-4 form-group" style="margin-left: -15px;">
                        <label>Location</label>
                        @* <input id="Location" type="text" class="form-control" /> *@
                        @Html.DropDownList("CityId", null, "--Select City--", htmlAttributes: new { @class = "form-control" })
                    </div>
                    <div class="col-sm-4 form-group">
                        <a href="javascript:;" style="margin-top: 24px;" onclick="getReport()" class="btn btn-primary">Get Report</a>
                    </div>

                    <table class="table table-bordered table-striped example">
                        <thead>
                            <tr class="info">
                                <th>App No</th>
                                <th>Sales Rep Id</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Mobile No</th>
                                <th>Date</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.Id</td>
                                    <td>@item.EmpCode</td>                                                                                                     
                                    <td>@item.FullName</td>
                                    <td>@item.Email</td>
                                    <td>@item.PhoneNumber</td>
                                    <td>@item.CreatedDate.ToString("dd MMM yyyy hh:mm tt")</td>
                                    <td>
                                        <a asp-controller="Enquiry" asp-action="Details" 
                                        asp-route-id="@item.Id" class="btn btn-primary" title="Delete Record">
                                            <i class="fa fa-eye"></i>
                                        </a>                                
                                    </td>
                                </tr>
                            }

                        </tbody>
                    </table>
                </form>
            </div>
        </div>
    </div>
</div>


@section Scripts
{
    <script type="text/javascript">
        function getReport()
        {
            var location = $("#CityId").val();
            
            if(location=="" || location === undefined || location == null)
                window.location = "/Reports/LocationWise";
            else
                window.location = "/Reports/LocationWise/" + location;
        }
    </script>
}

Views/Reports/Period.cshtml
@model IEnumerable<Enquiry>

@{
    ViewData["Title"] = "Period Report";
    ViewData["ActivePage"] = "Reports";    
}

<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-bd ">
            <div class="panel-heading">
                <div class="btn-group" id="buttonlist">
                    Period Report
                </div>
            </div>
            <div class="panel-body">
                <form class="col-sm-12">
                    <div class="col-sm-4 form-group" style="margin-left: -15px;">
                        <label>Select From Date</label>
                        <input id="txtFDate" type="date" class="form-control" />
                    </div>
                    <div class="col-sm-4 form-group">
                        <label>Select To Date</label>
                        <input id="txtTDate" type="date" class="form-control" />
                    </div>
                    <div class="col-sm-4 form-group">
                        <a href="javascript:;" style="margin-top: 24px;" onclick="getReport()" class="btn btn-primary">Get Report</a>
                    </div>

                    <table class="table table-bordered table-striped example">
                        <thead>
                            <tr class="info">
                                <th>App No</th>
                                <th>Sales Rep Id</th>
                                <th>Full Name</th>
                                <th>Email</th>
                                <th>Mobile No</th>
                                <th>Date</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.Id</td>
                                    <td>@item.EmpCode</td>                                                                                                     
                                    <td>@item.FullName</td>
                                    <td>@item.Email</td>
                                    <td>@item.PhoneNumber</td>
                                    <td>@item.CreatedDate.ToString("dd MMM yyyy hh:mm tt")</td>
                                    <td>
                                        <a asp-controller="Enquiry" asp-action="Details" 
                                        asp-route-id="@item.Id" class="btn btn-primary" title="Delete Record">
                                            <i class="fa fa-eye"></i>
                                        </a>                                  
                                    </td>
                                </tr>
                            }

                        </tbody>
                    </table>
                </form>
            </div>
        </div>
    </div>
</div>


@section Scripts
{
    <script type="text/javascript">
        function getReport()
        {
            var fdate = $("#txtFDate").val();
            var tdate = $("#txtTDate").val();
            
            if(fdate=="" || fdate === undefined || fdate == null)
            {
                alert('Please enter from date to fetch report.');
                return false;
            }

            if(tdate=="" || tdate === undefined || tdate == null)
            {
                alert('Please enter to date to fetch report.');
                return false;
            }

            window.location = "/Reports/Period?fromdate=" + fdate + "&todate=" + tdate;
        }
    </script>
}

Views/Reports/UserWise.cshtml
@model IEnumerable<Enquiry>

@{
    ViewData["Title"] = "User Wise Report";
    ViewData["ActivePage"] = "Reports";    
}

<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-bd ">
            <div class="panel-heading">
                <div class="btn-group" id="buttonlist">
                    User Wise Report
                </div>
            </div>
            <div class="panel-body">
                <form class="col-sm-12">
                    <div class="col-sm-4 form-group" style="margin-left: -15px;">
                        <label>Sales Rep Id</label>
                        @Html.DropDownList("EmployeeId", null, "--Select Sales Rep Id--", htmlAttributes: new { @class = "form-control" })
                    </div>
                    <div class="col-sm-4 form-group">
                        <a href="javascript:;" style="margin-top: 24px;" onclick="getReport()" class="btn btn-primary">Get Report</a>
                    </div>

                    <table class="table table-bordered table-striped example">
                        <thead>
                            <tr class="info">
                                <th>App No</th>
                                <th>Sales Rep Id</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Mobile No</th>
                                <th>Date</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.Id</td>
                                    <td>@item.EmpCode</td>                                                                                                     
                                    <td>@item.FullName</td>
                                    <td>@item.Email</td>
                                    <td>@item.PhoneNumber</td>
                                    <td>@item.CreatedDate.ToString("dd MMM yyyy hh:mm tt")</td>
                                    <td>
                                        <a asp-controller="Enquiry" asp-action="Details" 
                                        asp-route-id="@item.Id" class="btn btn-primary" title="Delete Record">
                                            <i class="fa fa-eye"></i>
                                        </a>                                 
                                    </td>
                                </tr>
                            }

                        </tbody>
                    </table>
                </form>
            </div>
        </div>
    </div>
</div>


@section Scripts
{
    <script type="text/javascript">
        function getReport()
        {
            var user = $("#EmployeeId").val();
            
            if(user=="" || user === undefined || user == null)
            {
                window.location = "/Reports/UserWise";
                return false;
            }

            window.location = "/Reports/UserWise/" + user;
        }
    </script>
}

Views/Reports/Weekly.cshtml
@model IEnumerable<Enquiry>

@{
    ViewData["Title"] = "User Wise Report";
    ViewData["ActivePage"] = "Reports";    
}

<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-bd ">
            <div class="panel-heading">
                <div class="btn-group" id="buttonlist">
                    Weekly Report
                </div>
            </div>
            <div class="panel-body">
                <form class="col-sm-12">
                    <div class="col-sm-4 form-group" style="margin-left: -15px;">
                        <label>Select Date</label>
                        <input id="txtDate" type="date" class="form-control" />
                    </div>
                    <div class="col-sm-4 form-group">
                        <a href="javascript:;" style="margin-top: 24px;" onclick="getReport()" class="btn btn-primary">Get Report</a>
                    </div>

                    <table class="table table-bordered table-striped example">
                        <thead>
                            <tr class="info">
                                <th>App No</th>
                                <th>Sales Rep Id</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Mobile No</th>
                                <th>Date</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.Id</td>
                                    <td>@item.EmpCode</td>                                                                                                     
                                    <td>@item.FullName</td>
                                    <td>@item.Email</td>
                                    <td>@item.PhoneNumber</td>
                                    <td>@item.CreatedDate.ToString("dd MMM yyyy hh:mm tt")</td>
                                    <td>
                                        <a asp-controller="Enquiry" asp-action="Details" 
                                        asp-route-id="@item.Id" class="btn btn-primary" title="Delete Record">
                                            <i class="fa fa-eye"></i>
                                        </a>                                     
                                    </td>
                                </tr>
                            }

                        </tbody>
                    </table>
                </form>
            </div>
        </div>
    </div>
</div>


@section Scripts
{
    <script type="text/javascript">
        function getReport()
        {
            var date = $("#txtDate").val();
            
            if(date=="" || date === undefined || date == null)
            {
                alert('Please enter date to fetch report.');
                return false;
            }

            window.location = "/Reports/Weekly/" + date;
        }
    </script>
}

Views/Reports/Yearly.cshtml
@model IEnumerable<Enquiry>

@{
    ViewData["Title"] = "Yearly Report";
    ViewData["ActivePage"] = "Reports";    
}

<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-bd ">
            <div class="panel-heading">
                <div class="btn-group" id="buttonlist">
                    Yearly Report
                </div>
            </div>
            <div class="panel-body">
                <form class="col-sm-12">
                    <div class="col-sm-4 form-group" style="margin-left: -15px;">
                        <label>Year</label>
                        @* @Html.DropDownList("Year", null, "--Select Year--", htmlAttributes: new { @class = "form-control" }) *@
                        @* <input id="txtYear" type="text" maxlength="4" class="form-control" /> *@
                        <select id="txtYear" class="form-control">
                            <option value="2015">2015</option>
                            <option value="2016">2016</option>
                            <option value="2017">2017</option>
                            <option value="2018">2018</option>
                            <option value="2019">2019</option>
                            <option value="2020">2020</option>                            
                            <option value="2020">2020</option>
                            <option value="2021">2021</option>
                            <option value="2022">2022</option>
                            <option value="2023">2023</option>
                            <option value="2024">2024</option>
                            <option value="2025">2025</option>
                            <option value="2026">2026</option>
                            <option value="2027">2027</option>
                            <option value="2028">2028</option>
                            <option value="2029">2029</option>
                            <option value="2030">2030</option>
                        </select>
                    </div>
                    <div class="col-sm-4 form-group">
                        <a href="javascript:;" style="margin-top: 24px;" onclick="getReport()" class="btn btn-primary">Get Report</a>
                    </div>

                    <table class="table table-bordered table-striped example">
                        <thead>
                            <tr class="info">
                                <th>App No</th>
                                <th>Sales Rep Id</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Mobile No</th>                                
                                <th>Date</th>                                
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.Id</td>
                                    <td>@item.EmpCode</td>                                                                                                     
                                    <td>@item.FullName</td>
                                    <td>@item.Email</td>
                                    <td>@item.PhoneNumber</td>
                                    <td>@item.CreatedDate.ToString("dd MMM yyyy hh:mm tt") </td>
                                    <td>
                                        <a asp-controller="Enquiry" asp-action="Details" 
                                        asp-route-id="@item.Id" class="btn btn-primary" title="Delete Record">
                                            <i class="fa fa-eye"></i>
                                        </a>                                                                            
                                    </td>
                                </tr>
                            }

                        </tbody>
                    </table>
                </form>
            </div>
        </div>
    </div>
</div>


@section Scripts
{
    <script type="text/javascript">
        function getReport()
        {
            var year = $("#txtYear").val();
            
            if(year=="" || year === undefined || year == null)
            {
                alert('Please enter year to fetch report.');
                return false;
            }

            window.location = "/Reports/Yearly/" + year;
        }

    </script>

}